apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "universal-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- .Values.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "universal-app.selectorLabels" . | nindent 4 }}
