{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- if .Values.route.tls.enabled }}
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: {{ .Values.route.tls.secretName }}
  {{- end }}
spec:
  to:
    kind: Service
    name: {{ include "common.names.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  host: {{ .Values.route.host }}
  port:
    targetPort: http-stats
{{- end -}}