{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: openshift-operators
  labels:
    {{- include "argocd-applications.labels" $ | nindent 4 }}
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  sources:
    - repoURL: {{ ((.repositories).charts).url | default $.Values.repositories.charts.url }}
      path: {{ .chart }}
      targetRevision: {{ ((.repositories).charts).revision | default $.Values.repositories.charts.revision }}
      helm:
        releaseName: {{ .name }}
        valueFiles:
        - {{ .values }}
    - repoURL: {{ ((.repositories).values).url | default $.Values.repositories.values.url }}
      ref: values
      targetRevision: {{ ((.repositories).values).revision | default $.Values.repositories.values.revision }}
{{- end }}