{{- if .Values.route.tls.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
spec:
  dnsNames:
    - {{ .Values.route.host }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.route.tls.certificate.issuer }}
  secretName: {{ .Values.route.tls.secretName }}
{{- end -}}