apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ $.Values.app.key | quote }}

  DB_USERNAME: {{ $.Values.database.username | quote }}
  DB_PASSWORD: {{ $.Values.database.password | quote }}

  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ $.Values.redis.password | quote }}
  {{- end }}

  {{- if .Values.mail.enabled }}
  MAIL_USERNAME: {{ $.Values.mail.username | quote }}
  MAIL_PASSWORD: {{ $.Values.mail.password | quote }}
  {{- end }}

  {{- if .Values.sentry.enabled -}}
  SENTRY_LARAVEL_DSN: {{ $.Values.sentry.dsn | quote }}
  {{- end }}

  {{- if .Values.secrets -}}
  {{- range $k, $v := .secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}