apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: http
      protocol: TCP
      port: 15672
      targetPort: http
