apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ $.Values.spring.profiles.active | quote }}
  SERVER_PORT: '8080'

  DATASOURCE_URL: {{ $.Values.datasource.url | quote }}
  {{- if .Values.config -}}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}