apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATASOURCE_USERNAME: {{ .Values.datasource.username | quote }}
  DATASOURCE_PASSWORD: {{ .Values.datasource.password | quote }}
  {{- if .Values.secrets -}}
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}