{{- range $i, $ingress := .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $i }}
  labels:
    {{- include "universal-app.labels" $ | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ $ingress.host }}
      secretName: {{ $.Release.Name }}-tls
  rules:
    - host: {{ $ingress.host }}
      http:
        paths:
          - path: {{ $ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ingress.service.name | default $.Release.Name }}
                port:
                  name: {{ $ingress.service.port }}
{{- end }}